version: 2.1

jobs:
  test:    
    docker:
      - image: cimg/node:17.0.1    
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm install"
      - run:
          name: "Run tests"
          command: "yarn test"

workflows:
  test-workflow:
    jobs:
      - test
